# Use latest Node for this
image: node:latest

# Basic process is as follows
# 1. Create temp .public folder
# 2. Copy everything in the root dir to the .public folder
# 3. Rename .public to public (This is part of the template ¯\_(ツ)_/¯ )
# 4. Install tiddlywiki node commands
# 5. Use tiddlywiki commands to export all sites as static files, along with the css
# 6. Export the public folder as an artifact
pages:
  cache:
    paths:
      - node_modules
  script:
    - mkdir public
    - cp index.html public/index.html
    - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/master/download?job=pages"'
    - unzip artifacts.zip -d artifacts
    - mv artifacts/public/images public
    - npm install -g tiddlywiki
    - tiddlywiki --load index.html --output public --savetiddlers [is[image]!is[system]] images
    - tiddlywiki --load index.html --output public --setfield [is[image]![system]] _canonical_uri $:/core/templates/canonical-uri-external-image text/plain --setfield [is[image]!is[system]] text "" text/plain --rendertiddler $:/core/save/all imagetest.html text/plain
#    - tiddlywiki --verbose --load index.html --output ./public --rendertiddlers [!is[system]] $:/core/templates/static.tiddler.html static text/plain
#    - tiddlywiki --verbose --load index.html --output ./public --rendertiddler $:/core/templates/static.template.css static/static.css text/plain
  artifacts:
    paths:
      - public
  only:
    - master
  allow_falure: true
