# Use latest Node for this
image: node:latest

# Basic process is as follows:
#   Create public folder
#   Install TiddlyWiki node commands
#   Save all images
#   Add _canonical_uri to all images
#   Clear data from all the images
#   Enable readonly mode
#   Delete the codemirror plugin
#   Delete state tiddlers
#   Save the output to ./public/index.html

pages:
  cache:
    paths:
      - node_modules
  script:
    - mkdir public
    - npm install -g tiddlywiki
    - tiddlywiki --load index.html --output public 
        --savetiddlers [is[image]] images
        --setfield [is[image]] _canonical_uri $:/core/templates/canonical-uri-external-image text/plain 
        --setfield [is[image]] text "" text/plain 
        --setfield $:/custom/readonly/control readonly $:/custom/booleans/true text/plain 
        --deletetiddlers [prefix[$:/plugins/tiddlywiki/codemirror]]
        --deletetiddlers [prefix[$:/custom/state/]]
        --deletetiddlers [prefix[$:/state/]]
        --rendertiddler $:/core/save/all index.html text/plain
#    - tiddlywiki --verbose --load index.html --output ./public --rendertiddlers [!is[system]] $:/core/templates/static.tiddler.html static text/plain
#    - tiddlywiki --verbose --load index.html --output ./public --rendertiddler $:/core/templates/static.template.css static/static.css text/plain
  artifacts:
    paths:
      - public
  only:
    - master

