# Use latest Node for this
image: node:latest

# Basic process is as follows:
#   Create public dir with private subdir
#   copy index.html and robots.txt 
#   Install TiddlyWiki node commands
#   Save all images
#   Save the favicon.ico to root (for iOS/Mac browsers to detect)
#   Add _canonical_uri to all images
#   Clear data from all the images
#   Enable readonly mode
#   Delete the codemirror plugin
#   Delete state tiddlers
#   Save the output to ./public/index.html

pages:
  cache:
    paths:
      - node_modules
  script:
    - mkdir -p ./public/edit
    - cp index.html ./public/edit/
    - cp robots.txt ./public/
    - npm install -g tiddlywiki
    - tiddlywiki --load index.html --output public 
        --savetiddlers [is[image]] images
        --savetiddler $:/favicon.ico favicon.ico
        --setfield [is[image]!is[system]] _canonical_uri $:/core/templates/canonical-uri-external-image text/plain 
        --setfield [is[image]!is[system]] text "" text/plain
        --setfield $:/custom/readonly/control readonly $:/custom/booleans/true text/plain 
        --deletetiddlers [prefix[$:/plugins/tiddlywiki/codemirror]]
        --deletetiddlers [prefix[$:/custom/state/]]
        --deletetiddlers [prefix[$:/state/]!prefix[$:/state/tab/sidebar]]
        --deletetiddlers [prefix[$:/temp/]]
        --rendertiddler $:/core/save/all index.html text/plain
#    - tiddlywiki --verbose --load index.html --output ./public --rendertiddlers [!is[system]] $:/core/templates/static.tiddler.html static text/plain
#    - tiddlywiki --verbose --load index.html --output ./public --rendertiddler $:/core/templates/static.template.css static/static.css text/plain
  artifacts:
    paths:
      - public
  only:
    - master

